modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="eic"
version="1.0.0"
displayName="EIC"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="LatteSyobon, MCreator"

[[dependencies.eic]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




